name: Testing
on: push

jobs:
  test_projects:
  runs-on: ubuntu-latest
  steps:
  - users: actions/checkout@v2
  - name: Run Django unit tests
    run:
      pip install --user Django
      python manage.py test