name: Testing
on: push

jobs:
  test_projects2:
  runs-on: ubuntu-latest
  steps:
  - users: actions/checkout@v2
  - name: Run Django unit tests
    run:
      pip3 install --user Django
      python3 manage.py test
